- name: Build for iOS Simulator
        working-directory: ./iOS
        run: swift build -v -Xswiftc -target -Xswiftc arm64-apple-ios18.0-simulator -Xswiftc -sdk -Xswiftc $(xcrun --sdk iphonesimulator --show-sdk-path)
